language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "9"
  - "8"

addons:
  apt:
    packages:
      - oracle-java8-set-default

services:
  - mongodb

env:
  - ES=2
  - ES=5

before_install:
  - if [ "$ES" -eq "2" ]; then echo "DOWNLOADING V2"; curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.2.0/elasticsearch-2.2.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.2.0.deb ; fi
  - if [ "$ES" -eq "5" ]; then echo "DOWNLOADING V5"; curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.0.0.deb ; fi
  - 'echo "script.inline: true" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo cat /etc/elasticsearch/elasticsearch.yml
  - sudo service elasticsearch start
  - sleep 5
  - sudo service elasticsearch status

script:
  - if [ "$ES" -eq "2" ]; then echo "RUNNING V2"; npm run-script test-v2-covered ; fi
  - if [ "$ES" -eq "5" ]; then echo "RUNNING V5"; npm run-script test-v5-covered ; fi


after_success:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then npm run semantic-release; fi
